### ISSUE TITLE
Unificar grafico matcheo con preview

### ISSUE THREAD

**Issue by Sansanto2000** [Sansanto2000/AppAlineado#27]
Actualmente mostramos el espectro de lámpara observada e inmediatamente debajo la preview de su versión calibrada. Toma mucho espacio vertical.

Ajustar el código para mostrar la misma información en un solo gráfico, teniendo el gráfico normal del espectro al que le añadimos un segundo eje X con la muestra de cómo sería la version calibrada.

![imagen](https://github.com/user-attachments/assets/61a035d5-55ed-4201-82fb-34cc3ea651bf)

**Comment by Sansanto2000** [comment]
Construí esta versión:
![image](https://github.com/user-attachments/assets/b092cdfa-374d-4795-87b0-f3cae341aca7)

Funciona bien, pero siento que se pierde un poco el que se pueda apreciar la nueva escala respecto a cómo funcionaba la preview antigua:
![image](https://github.com/user-attachments/assets/cf71a3b9-c52b-4b6b-8209-d18b6007c9f2)
![image](https://github.com/user-attachments/assets/09a35bc0-f34a-4c4b-ab6c-7fec09d9240f)

Osea, la antigua deformaba lo necesario la función para que se aprecie cómo se comporta la nueva asignación de forma lineal. 
La versión actual pone los valores donde corresponde pero no es evidente para el observador que ahora los datos en el eje de longitudes de onda no siempre van a respetar los mismos intervalos entre sí.

¿Opinion @facundoq @JuanM04 ?

**Comment by facundoq** [comment]
Para mí si pones los dos ejes abajo se entiende mejor..y en el tradeoff de
sacar un gráfico le gana
